[project]
name = "video-depth-anything"
version = "0.1.0"
description = "Unofficial installable wrapper for https://github.com/DepthAnything/Video-Depth-Anything"
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["video_depth_anything"]
